version: '3'

services:
  apache:
    build:
      context: .
    container_name: php
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./:/var/www/html

  composer:
    container_name: composer_install
    image: composer
    volumes:
      - ./:/app
    command: composer install --ignore-platform-reqs